export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import Nav from "./components/nav/nav";
import HeadComponent from "./components/head-component/page";
import FrameComponent from "./components/frame-component/frame-component";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeadComponent></HeadComponent>
        <Nav></Nav>
        <FrameComponent props={children}></FrameComponent>
      </body>
    </html>
  );
}
