export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import Nav from "./components/nav/nav";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav></Nav>
        {children}
      </body>
    </html>
  );
}
